"""

Link - https://leetcode.com/problems/find-the-difference/


Problem Description:

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

"""


#     Time Complexity    Space Complexity
#          O(N)               O(N)



class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        alpha = dict()
        for each_s in s:
            if each_s not in alpha:
                alpha[each_s] = 1
            else:
                alpha[each_s]+=1
        for each_t in t:
            if each_t in alpha:
                alpha[each_t] -=1
            else:
                alpha[each_t] = 1
        string=""
        for key,value in alpha.items():
            if(value==1 or value==-1):
                string+=key
        print(string)
        return string
      
      
